apps/admin/dashboard/urls.py
from . import views
from django.urls import path

app_name = 'dashboard'

urlpatterns =[
    path('', views.dashboard, name='dashboard'),
]

project_parish_portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.admin.dashboard.urls')),
    path('priest/',include('apps.admin.priest.urls')),
    path('parish/',include('apps.admin.parish.urls')),
    path('family_unit/',include('apps.admin.family_unit.urls')),
    path('family_details/',include('apps.admin.family_details.urls'))
]

templates/layouts/apps.html
{% load static tailwind_tags %}
{% tailwind_css %}

<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Diocese of Adilabad</title>
	<!-- <link href="{% static 'css/style.bundle.css' %}?time={% now 'h:i:s' %}" rel="stylesheet" type="text/css" /> -->
	<link rel="stylesheet" href="https://cdn.datatables.net/2.1.7/css/dataTables.tailwindcss.css">
	<link rel="icon" href="{% static 'images/adilabad_bg' %}" type="image/x-icon">
	<script src="{% static 'plugins/global/plugins.bundle.js' %}?time={% now 'h:i:s' %}"></script>
	<script src="{% static 'js/scripts.bundle.js' %}?time={% now 'h:i:s' %}"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://cdn.datatables.net/2.1.7/js/dataTables.js"></script>
	<script src="https://cdn.datatables.net/2.1.7/js/dataTables.tailwindcss.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/smooth-scroll@16.1.3/dist/smooth-scroll.polyfills.min.js"></script>
</head>

<body class="h-screen overflow-hidden">
	<div class="flex h-screen admin-interface">
		<!-- Sidebar -->
		{% include 'layouts/sidemenu.html' %}
		<div class="main-content flex flex-col w-full overflow-y-auto relative">
			<!-- Header Section -->
			{% include 'layouts/header.html' %}
			<!-- Main Content -->
			<div class="flex h-screen">
				<div class="flex flex-col w-full">
					<main class="flex-1 p-7 lg:p-8 bg-gray-blue">
						<!-- Content section -->
						{% block content %}
						{% endblock content %}
					</main>
				</div>
			</div>
		</div>
</body>

<script src="{% static 'js/custom/utils/form-validation.js' %}"></script>
<script src="{% static 'js/custom/utils/modal.js' %}"></script>
<script src="{% static 'js/custom/utils/toast.js' %}"></script>
<script src="{% static 'js/custom/utils/datatable/datatable-defaults.js' %}"></script>
<script src="{% static 'js/custom/utils/datatable/sort-filter.js' %}"></script>
</html>

{% block script %}

{% endblock script %}

templates/layouts/base_create.html
{% extends 'layouts/apps.html' %} 
{% load static %}

<!-- Profile page layout -->
{% block content %}
<!-- Breadcrumb -->
{% include 'layouts/partials/breadcrumbs.html' %}

<h1>{% block heading %} {% endblock %}</h1>

<!-- Form -->
<div class="mt-6 border border-gray-200 rounded-lg overflow-hidden">
    <h2 class="text-base text-zinc-500 font-medium bg-gray-medium px-8 py-4">
        {% block sub-heading %} {% endblock %}
    </h2>
    {% block form %} {% endblock %}
</div>

{% endblock content %}

templates/layouts/base_list.html
{% extends 'layouts/apps.html' %}
{% load static %}

<!-- List page layout -->
{% block content %}
<!-- Breadcrumb -->
{% include 'layouts/partials/breadcrumbs.html' %}

{% block profile-section %} {% endblock %}

<h1>
  {% block heading %} {% endblock %}
</h1>

<!-- Table actions -->
<div class="mt-6 flex justify-between items-center">
  <!-- Custom Search Button -->
  {% block table-search %} {% endblock %}
  <!-- Add new Button -->
  {% block addbutton %} {% endblock %}
</div>
<div class="my-4 flex justify-between items-center">
  <!-- Total count -->
  {% block total-count %} {% endblock %}
  <!-- Table actions -->
  <div class="flex items-center gap-x-3">
    {% block table-actions %} {% endblock %}
  </div>
</div>

<!-- Table -->
<div class="datatable mt-4">
  {% block table %} {% endblock %}
</div>

<!-- Selected Rows Count -->
<div class="-mt-14 text-sm text-zinc-600">
  {% block selected %} {% endblock %}
</div>
{% endblock content %}

templates/layouts/base_profile.html
{% extends 'layouts/apps.html' %}
{% load static %}

<!-- Profile page layout -->
{% block content %}
<!-- Breadcrumb -->
{% include 'layouts/partials/breadcrumbs.html' %}

<h1>
    {% block heading %} {% endblock %}
</h1>

<div class="my-6 rounded-md border border-[#eeeded] overflow-hidden">
    <div class="flex justify-between items-center bg-gray-100 pl-8 pr-2.5 py-2.5">
        <h2 class="text-zinc-500">{% block sub-heading %} {% endblock %}</h2>
        <div class="flex gap-x-4">
            <!-- Delete & Edit Buttons -->
            {% block buttons %} {% endblock %}

        </div>
    </div>
    <!-- Profile section -->
    <div class="bg-white px-8 py-14 flex flex-col gap-y-14">
        <div class="grid grid-cols-2 gap-x-8 lg:gap-x-24 max-w-4xl">
            {% block row1 %} {% endblock %}
        </div>
        {% block row2 %} {% endblock %}
    </div>
</div>
{% endblock content %}

templates/layouts/guest.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <!--begin::Head-->
  <head>
    <title>Alcan First Principles</title>
    <meta charset="utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--begin::Fonts-->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700"
    />
    <!--end::Fonts-->
    <!--begin::Global Stylesheets Bundle(used by all pages)-->
    <link
      href="{% static 'plugins/global/plugins.bundle.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <!-- <link
      href="{% static 'css/style.bundle.css' %}"
      rel="stylesheet"
      type="text/css"
    /> -->
    <!--end::Global Stylesheets Bundle-->
  </head>
  <!--end::Head-->
  <!--begin::Body-->
  <body id="kt_body" class="bg-body">
    <!--begin::Main-->
    {% block content %}{% endblock content %}
    <!--end::Main-->
    <!--begin::Javascript-->
    <script>
      var hostUrl = "{% static 'assets/' %}";
    </script>
    <!--begin::Global Javascript Bundle(used by all pages)-->
    <script src="{% static 'plugins/global/plugins.bundle.js' %}"></script>
    <script src="{% static 'js/scripts.bundle.js' %}"></script>
    <!--end::Global Javascript Bundle-->
    <!--begin::Page Custom Javascript(used by this page)-->
    {% comment %}
    <script src="{% static 'js/custom/authentication/sign-in/general.js' %}"></script>
    {% endcomment %}
    <!--end::Page Custom Javascript-->
    <!--end::Javascript-->

    <script>
      $.ajaxSetup({
        data: {
          csrfmiddlewaretoken: "{{ csrf_token }}",
        },
      });
    </script>

    {% block script %}{% endblock script %}
  </body>
  <!--end::Body-->
</html>

templates/layouts/header.html
{% load static %}
<!-- Header Section -->
<div
  class="flex items-center justify-between lg:justify-end sticky top-0 px-7 lg:px-10 bg-white min-h-[90px] border-b border-b-gray-light z-20"
>
  <div id="hamburger-menu" class="hamburger-menu lg:hidden">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="size-6 text-gray-400"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
      />
    </svg>
  </div>
  <div class="user-info flex">
    <div
      id="user-avatar-dropdown"
      class="user-info-wrapper relative flex items-center mr-3 rounded-md py-2 px-3 hover:bg-zinc-100 hover:cursor-pointer"
    >
      <!-- User Icon -->
      <img class="" src="{% static 'images/user_icon.svg' %}" alt="User Icon" />
      <!-- User Name -->
      <div class="flex flex-col mx-3">
        <p class="text-zinc-950 font-medium text-sm">John Doe</p>
        <span class="text-zinc-500 font-normal text-xs">Admin</span>
      </div>
      <!-- User dropdown -->
      <img
        class="self-start cursor-pointer"
        id="header-dropdown-icon"
        src="{% static 'images/layout_dropdown_arrow.svg' %}"
        alt="dropdown arrow"
      />
      <!-- Dropdown menu -->
      <a
        href=""
        class="absolute rounded border border-zinc-200 flex hidden items-center min-w-[171] pl-5 py-3 z-10 mt-2 top-[54] left-0 w-40 bg-white shadow-lg hover:bg-gray-100"
        id="header-dropdown"
        role="menu"
      >
        <img
          src="{% static 'images/log_out_icon.svg' %}"
          alt="Log out Icon"
          class=""
        />
        <div class="py-1" role="none">
          <p class="block px-2 text-sm" role="menuitem">Log out</p>
        </div>
      </a>
    </div>
  </div>
</div>

{% block script %}
<script src="{% static 'js/custom/pages/layout/header.js' %}?time={% now 'h:i:s' %}"></script>
{% endblock script %}

templates/layouts/sidemenu.html
{% load static %}

<!-- Sidebar -->
<div id="sidenav" class="max-lg:hidden transition-[min-width] duration-300 ease-in-out min-w-[280px] bg-white flex flex-col border-r border-r-gray-light sticky top-0 h-screen overflow-y-auto">
  <!-- Logo Section -->
  <div class="flex items-center justify-between p-5 min-h-[90px] border-b border-b-gray-light">
    <div class="flex items-center">
      <img src="{% static 'images/adilabad_bg.jpg' %}" alt="Logo" class="h-10" />
      <span class="menu-text px-2 font-bold text-red-200 text-base">Adilabad Diocese</span>
    </div>
    <!-- Collapse Icon -->
    <button id="collapseBtn" class="max-lg:hidden">
      <img src="{% static 'images/sidenav_collapse.svg' %}" id="collapseIcon" alt="Collapse Icon" class="w-5 h-3" />
    </button>
    <button id="closeBtn" class="lg:hidden">
      <svg class="w-4 h-4 text-gray-500 close-icon">
        <use href="{% static 'images/cross.svg' %}#Vector"></use>
      </svg>
    </button>
  </div>
  <!-- Sidebar Links with Icons -->
  <nav id="sidenav-links"
    class="flex-grow overflow-y-auto font-medium text-sm {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}">
    <!-- Dashboard Menu -->
    <a href="{% url 'dashboard:dashboard' %}"
      class="nav-menu h-10 rounded flex items-start mx-5 my-5 p-2 group hover:bg-blue-100 {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}">
      <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-500">
        <use href="{% static 'images/dashboard_icon.svg' %}#Dashboard"></use>
      </svg>
      <span class="menu-text ml-3">Dashboard</span>
    </a>
    <!-- Priest Menu -->
    <div class="nav-menu flex flex-col items-start mx-5 my-5 overflow-hidden">
      <button id="organizationToggle" class="h-10 flex rounded items-center w-full p-2 group hover:bg-blue-100">
        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-500">
          <use href="{% static 'images/roles_icon.svg' %}#Roles"></use>
        </svg>
        <span class="menu-text ml-3">Priest</span>
        <img src="{% static 'images/layout_dropdown_arrow.svg' %}" id="sidenav-dropdown-icon" alt="dropdown arrow"
          class="ml-auto menu-text" />
      </button>
      <div id="organizationMenu" class="hidden w-full flex-col space-y-3 pl-8 mt-4 font-medium text-bayouxBlue">
        <a href="{% url 'priest:priest.create' %}"
          class="block p-2 rounded hover:bg-blue-100 {% if request.resolver_match.url_name == 'priest.create' %}active{% endif %}">Add
          Priest</a>
        <a href="{% url 'priest:priest.index' %}"
          class="block p-2 rounded hover:bg-blue-100 {% if request.resolver_match.url_name == 'priest.index' %}active{% endif %}">Priest
          List</a>
      </div>
    </div>
    <!-- Parish Menu -->
    <div class="nav-menu flex flex-col items-start mx-5 my-5 overflow-hidden">
      <button id="usersToggle" class="h-10 flex rounded items-center w-full p-2 group hover:bg-blue-100">
        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-500">
          <use href="{% static 'images/users_icon.svg' %}#Users"></use>
        </svg>
        <span class="menu-text ml-3">Parish</span>
        <img src="{% static 'images/layout_dropdown_arrow.svg' %}" alt="dropdown arrow" class="ml-auto menu-text" />
      </button>
      <div id="usersMenu" class="hidden w-full flex-col space-y-3 pl-8 mt-4 font-medium text-bayouxBlue">
        <a href="{% url 'parish:parish.create' %}"
          class="block p-2 rounded hover:bg-blue-100 {% if request.resolver_match.url_name == 'roles.create' %}active{% endif %}">Add
          Parish</a>
        <a href="{% url 'parish:parish.list' %}"
          class="block p-2 rounded hover:bg-blue-100 {% if request.resolver_match.url_name == 'roles.index' %}active{% endif %}">Parish
          List</a>
      </div>
    </div>
    <!-- Family Unit Menu -->
    <div class="nav-menu flex flex-col items-start mx-5 my-5 overflow-hidden">
      <button id="observationsToggle" class="h-10 flex rounded items-center w-full p-2 group hover:bg-blue-100">
        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-500">
          <use href="{% static 'images/roles_icon.svg' %}#Roles"></use>
        </svg>
        <span class="menu-text ml-3">Family Unit</span>
        <img src="{% static 'images/layout_dropdown_arrow.svg' %}" alt="dropdown arrow" class="ml-auto menu-text" />
      </button>
      <div id="observationsMenu" class="hidden w-full flex-col space-y-3 pl-8 mt-4 font-medium text-bayouxBlue">
        <a href="{% url 'family_unit:family_unit.create' %}"
          class="block p-2 rounded hover:bg-blue-100 {% if request.resolver_match.url_name == 'observation.create' %}active{% endif %}">Add
          Family Unit</a>
        <a href="{% url 'family_unit:family_unit.list' %}"
          class="block p-2 rounded hover:bg-blue-100 {% if request.resolver_match.url_name == 'observation.index' %}active{% endif %}">Family
          Unit List</a>
      </div>
    </div>
    <!-- Family Menu -->
    <div class="nav-menu flex flex-col items-start mx-5 my-5 overflow-hidden">
      <button id="familyToggle" class="h-10 flex rounded items-center w-full p-2 group hover:bg-blue-100">
        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-500">
          <use href="{% static 'images/observations_icon.svg' %}#Observations"></use>
        </svg>
        <span class="menu-text ml-3">Family Details</span>
        <img src="{% static 'images/layout_dropdown_arrow.svg' %}" alt="dropdown arrow" class="ml-auto menu-text" />
      </button>
      <div id="familyMenu" class="hidden w-full flex-col space-y-3 pl-8 mt-4 font-medium text-bayouxBlue">
        <a href="{% url 'family_details:family_details.create' %}"
          class="block p-2 rounded hover:bg-blue-100 {% if request.resolver_match.url_name == 'checklist.create' %}active{% endif %}">Add
          Family</a>
        <a href="{% url 'family_details:family_details.list' %}"
          class="block p-2 rounded hover:bg-blue-100 {% if request.resolver_match.url_name == 'checklist.index' %}active{% endif %}">Family
          List</a>
      </div>
    </div>
  </nav>
</div>

{% block script %}
<script src="{% static 'js/custom/pages/layout/sidemenu.js' %}?time={% now 'h:i:s' %}"></script>
<style>
  #sidenav.collapsed {
    min-width: 80px;
  }

  .menu-text {
    transition: opacity 0.3s ease;
  }

  .menu-text.hidden {
    opacity: 0;
  }

  .nav-menu {
    transition: margin 0.3s ease;
  }

  .nav-menu img {
    transition: margin 0.3s ease;
  }

  .nav-menu img.centered-img {
    margin: auto;
  }

  .sidenav-open {
    display: block;
    position: fixed;
    /* Ensure it stays on top of the content */
    top: 0;
    left: 0;
    height: 100%;
    width: 250px;
    /* Or any width you desire */
    background-color: white;
    z-index: 100;
    /* Higher z-index than the content */
    transition: width 0.3s ease;
  }

  /* Content gets dimmed when sidenav is open */
  .main-content.overlay-active {
    filter: brightness(0.7);
    pointer-events: none;
    /* Prevent interaction with content while sidenav is open */
  }

  /* Optional: Optional background overlay effect */
  .main-content.overlay-active::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.5);
    /* Dimming effect */
    z-index: 99;
    /* Below sidenav */
    pointer-events: none;
    /* Allow clicks through the overlay */
  }
</style>
{% endblock script %}